### ISSUE TITLE
Missing de_vertigo overview picture

### ISSUE THREAD

**Issue by idoleat** [zoidbergwill/csgo-overviews#12]
The overview download link provided in the readme doesn't contain de_vertigo. Yeah I can find it by myself and put it in the folder, but it will be nice if files work out of the box. Thanks.

**Comment by idoleat** [comment]
I think there should be a way to automate the overview updating process. Since vertigo could still be changed frequently. XDD

**Comment by zoidyzoidzoid** [comment]
Thanks for the issue, @idoleat 

I'd love to figure out a way to automate it.

I've updated them: https://github.com/zoidbergwill/csgo-overviews/blob/master/overviews.md#de_vertigo

**Comment by zoidyzoidzoid** [comment]
Unfortunately steamdb exports of updates for CS:GO don't include `.dds` files, so we can't use those.

If you have any other ideas, I'd love to hear them.

**Comment by zoidyzoidzoid** [comment]
Gonna close this issue since we have de_vertigo and de_vertigo_lower from the latest update now. Thanks for your patience, since it's been a while since I updated this project.

**Comment by idoleat** [comment]
Thanks. 😃 I'll try in my free time
