### ISSUE TITLE
Update de_dust2

### ISSUE THREAD

**Issue by Linus4** [zoidbergwill/csgo-overviews#13]
There's been an update to de_dust2. Could you update the overview images?

**Comment by zoidyzoidzoid** [comment]
Hey @Linus4 

Thanks for the bug report.

I'll update them next time I'm at my PC where CS:GO is installed.

If you get can fetch me the de_dust2 .dds files from your installation of CS:GO in `common/Counter-Strike Global Offensive/csgo/resource/overviews` then I can update them.

**Comment by Linus4** [comment]
Sure, I've sent you an email.
